import type { Metadata } from 'next';
import { Playfair_Display, Inter } from 'next/font/google';
import './globals.css';
import NavBar from './components/NavBar';
import RecipeCard from './components/RecipeCard';

const playfair = Playfair_Display({
    subsets: ['latin'],
    weight: 'variable'
});

const inter = Inter({
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Epicurist',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${playfair.className} bg-stone-200 dark:bg-gray-900`}
            >
                <NavBar />
                {children}
            </body>
        </html>
    );
}
