import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import './globals.css';
import NavBar from './components/NavBar';

const playfair = Playfair_Display({
    subsets: ['latin'],
    weight: 'variable'
});

export const metadata: Metadata = {
    title: 'Epicura',
    description: 'Generated by create next app',
    icons: {
        icon: [
            {
                media: '(prefers-color-scheme: light)',
                url: '/Users/roryholmes/Documents/meal-planner/meal-planner/public/favicons/faviconBlack.ico',
                href: '/Users/roryholmes/Documents/meal-planner/meal-planner/public/favicons/faviconBlack.ico'
            },
            {
                media: '(prefers-color-scheme: dark)',
                url: '/favicons/faviconWhite.ico',
                href: '/favicons/faviconWhite.ico'
            }
        ]
    }
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${playfair.className} bg-stone-200 dark:bg-gray-900`}
            >
                <NavBar />
                {children}
            </body>
        </html>
    );
}
